name: Build & Deploy Release APK

on: 
  push:
    tags:
      - '*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4.1.7
    - name: setup jdk
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '18'
        distribution: 'adopt'
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Get local.properties from secrets
      run: echo "${{secrets.LOCAL_PROPERTIES }}" > $GITHUB_WORKSPACE/local.properties  
    - name: Build With Gradle
      run: ./gradlew build
    - name: Upload Release Build to Artifacts
      uses: actions/upload-artifact@v4.3.4
      with:
        name: release-artifacts
        path: |
          app/build/outputs/apk/debug/app-debug.apk
          
    - name: Create Github Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        prerelease: false
        files: |
            app/build/outputs/apk/debug/app-debug.apk
          
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: app
